# Generated by Django 3.0.2 on 2020-01-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('CUIT', models.CharField(max_length=13)),
                ('teléfono', models.CharField(max_length=10)),
                ('correo_electrónico', models.EmailField(max_length=100)),
                ('dirección', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
