# Generated by Django 3.0.2 on 2020-02-11 21:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('CUIT', models.CharField(max_length=13)),
                ('teléfono', models.CharField(max_length=10)),
                ('correo_electrónico', models.EmailField(max_length=100)),
                ('dirección', models.CharField(max_length=200)),
                ('deuda', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=9)),
                ('unidad_de_medida', models.CharField(choices=[('Litro', 'Litro'), ('Kilo', 'Kilo'), ('Gramo', 'Gramo'), ('Cm3', 'Cm3'), ('Unidad', 'Unidad')], max_length=200, null=True)),
                ('stock', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ('nombre',),
                'index_together': {('tipo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('numero', models.CharField(default='0000000000', max_length=10)),
                ('estado', models.CharField(choices=[('PAGA', 'PAGA'), ('IMPAGA', 'IMPAGA')], default='IMPAGA', max_length=200)),
                ('fecha_de_pago', model_utils.fields.MonitorField(blank=True, default=None, monitor='estado', null=True, verbose_name='Fecha de pago', when={'PAGA'})),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('tipo', models.CharField(choices=[('Factura A', 'Factura A'), ('Factura B', 'Factura B'), ('Factura C', 'Factura C')], default='Factura C', max_length=200)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Proveedor')),
            ],
            options={
                'ordering': ('estado',),
                'index_together': {('proveedor', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Producto')),
            ],
        ),
    ]
