# Generated by Django 3.0.2 on 2020-02-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='deuda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
