# Generated by Django 3.0.2 on 2020-03-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20200211_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='factura',
            field=models.IntegerField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.IntegerField(max_length=13),
        ),
    ]
