# Generated by Django 3.0.2 on 2020-03-16 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20200315_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Factura'),
        ),
    ]
