# Generated by Django 3.0.2 on 2020-01-22 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='factura',
            name='número',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=15),
        ),
    ]
