# Generated by Django 3.0.2 on 2020-03-18 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20200315_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Factura'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
