# Generated by Django 3.0.2 on 2020-01-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20200121_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='número',
            field=models.DecimalField(decimal_places=0, default='000000000000', max_digits=15),
        ),
    ]
