# Generated by Django 3.0.2 on 2020-03-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20200318_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
