# Generated by Django 3.0.2 on 2020-01-22 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_auto_20200121_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='número',
        ),
    ]
