# Generated by Django 3.0.2 on 2020-01-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_auto_20200121_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(choices=[(0, 'NO PAGO'), (1, 'PAGO')]),
        ),
    ]
