# Generated by Django 3.0.2 on 2020-01-24 00:44

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_auto_20200123_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='author',
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_de_pago',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='estado', null=True, verbose_name='date sent', when={'PAGO'}),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.IntegerField(choices=[('NOPAGO', 'nopago'), ('PAGO', 'pago')]),
        ),
    ]
