# Generated by Django 3.0.2 on 2020-01-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_auto_20200123_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
    ]
