# Generated by Django 3.0.2 on 2020-01-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_remove_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
