# Generated by Django 3.0.2 on 2020-01-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_factura_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
