# Generated by Django 3.0.2 on 2020-01-30 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_auto_20200126_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineaDeProducto',
            new_name='Detalle',
        ),
    ]
