# Generated by Django 3.0.2 on 2020-01-30 14:10

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0016_auto_20200129_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='producto',
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('Paga', 'Paga'), ('No Paga', 'No Paga')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_de_pago',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='estado', null=True, verbose_name='Fecha de pago', when={'Paga'}),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_de_medida',
            field=models.CharField(choices=[('Litro', 'Litro'), ('Kilo', 'Kilo'), ('Gramo', 'Gramo'), ('Cm3', 'Cm3'), ('Unidad', 'Unidad')], max_length=200, null=True),
        ),
    ]
