# Generated by Django 3.0.2 on 2020-01-30 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0017_auto_20200130_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.Producto'),
        ),
    ]
