# Generated by Django 3.0.2 on 2020-01-30 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0020_auto_20200130_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='precio',
        ),
        migrations.AddField(
            model_name='factura',
            name='detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Detalle'),
        ),
    ]
