# Generated by Django 3.0.2 on 2020-01-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0021_auto_20200130_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='producto',
        ),
    ]
