# Generated by Django 3.0.2 on 2020-01-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0022_auto_20200130_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
