# Generated by Django 3.0.2 on 2020-01-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0023_auto_20200130_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_de_medida',
            field=models.CharField(choices=[('Litro', 'Litro'), ('Kilo', 'Kilo'), ('Gramo', 'Gramo'), ('Cm3', 'Cm3'), ('Unidad', 'Unidad')], max_length=200, null=True),
        ),
    ]
