# Generated by Django 3.0.2 on 2020-01-30 19:15

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0024_auto_20200130_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('Paga', 'PAGA'), ('Impaga', 'IMPAGA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_de_pago',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='estado', null=True, verbose_name='Fecha de pago', when={'Impaga'}),
        ),
    ]
