# Generated by Django 3.0.2 on 2020-01-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0027_auto_20200130_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='factura',
            name='detalle',
        ),
        migrations.AddField(
            model_name='factura',
            name='detalle',
            field=models.ManyToManyField(blank=True, null=True, to='compras.Detalle'),
        ),
    ]
