# Generated by Django 3.0.2 on 2020-02-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0029_auto_20200130_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
