# Generated by Django 3.0.2 on 2020-02-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0031_factura_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='factura',
        ),
        migrations.AddField(
            model_name='factura',
            name='detalle',
            field=models.ManyToManyField(blank=True, null=True, to='compras.Detalle'),
        ),
    ]
