# Generated by Django 3.0.2 on 2020-02-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0040_detalle_factura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('nombre',)},
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='productos',
        ),
        migrations.AddField(
            model_name='factura',
            name='detalles',
            field=models.ManyToManyField(blank=True, null=True, to='compras.Detalle'),
        ),
        migrations.AlterIndexTogether(
            name='producto',
            index_together={('tipo', 'nombre')},
        ),
    ]
