# Generated by Django 3.0.2 on 2020-02-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0042_auto_20200206_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ('apellido',), 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='factura',
            name='productos',
            field=models.ManyToManyField(through='compras.Detalle', to='compras.Producto'),
        ),
    ]
