# Generated by Django 3.0.2 on 2020-02-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0043_auto_20200206_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='detalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='productos',
            field=models.ManyToManyField(blank=True, null=True, to='compras.Producto'),
        ),
    ]
