# Generated by Django 3.0.2 on 2020-02-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0044_auto_20200207_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='productos',
        ),
    ]
