# Generated by Django 3.0.2 on 2020-02-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0045_remove_factura_productos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ('total',)},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='deuda',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterIndexTogether(
            name='factura',
            index_together={('proveedor', 'estado')},
        ),
    ]
