# Generated by Django 3.0.2 on 2020-02-11 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0046_auto_20200211_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ('estado',)},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='deuda',
        ),
    ]
